@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package fathertoast.deadlyworld.common.core.registry.util;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;