@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.deadlyworld.api.client;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;