@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.deadlyworld.common.config;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;