@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package fathertoast.deadlyworld.common.block.infested;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;