@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package fathertoast.deadlyworld.common.core.registry.misc;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;