@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.deadlyworld.common.core;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;