@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package fathertoast.deadlyworld.client.renderer.decoy;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;