@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.deadlyworld.common.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;