@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.deadlyworld.common.fishpranks;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;