@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package fathertoast.deadlyworld.common.block.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;